CREATE TABLE `sf_dataset_fields` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `table_id` int unsigned NOT NULL,
  `name` varchar(150) NOT NULL,
  `title` varchar(150) NOT NULL,
  `sf_map_name` varchar(150) NOT NULL,
  `type` varchar(150) NOT NULL,
  `campaign_id` int DEFAULT NULL,
  `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `object` int unsigned NOT NULL,
  `alias_name` varchar(500) NOT NULL,
  `send_to_sf` TINYINT NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE KEY `UNQ_DATA_FIELDS` (`campaign_id`,`table_id`,`name`,`object`),
  KEY `FK_OBJECT` (`object`),
  KEY `FK_TABLE` (`table_id`),
  CONSTRAINT `FK_OBJECT` FOREIGN KEY (`object`) REFERENCES `sf_dataset_objects` (`id`),
  CONSTRAINT `FK_TABLE` FOREIGN KEY (`table_id`) REFERENCES `sf_dataset_tables` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;