CREATE TABLE `sf_dataset_sub_object_conditions` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `sub_object_id` int unsigned NOT NULL,
  `object_id` int unsigned NOT NULL,
  `apply_is_data` tinyint NOT NULL DEFAULT '0',
  `apply_is_data_conjunction_type` varchar(20) NOT NULL,
  `where_clause` varchar(500) NOT NULL,
  `groupby_clause` varchar(500) NOT NULL,
  `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `campaign_id` int DEFAULT NULL,
  `apply_table` int unsigned DEFAULT NULL,
  `apply_table_field` int unsigned DEFAULT NULL,
  `field_where_clause` varchar(500) DEFAULT NULL,
  `name` varchar(100) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_SB_OBJECT` (`sub_object_id`),
  KEY `FK_OBJECT_CONDITION` (`object_id`),
  KEY `FK_APPLY_TABLE` (`apply_table`),
  KEY `FK_APPLY_FIELD` (`apply_table_field`),
  CONSTRAINT `FK_APPLY_FIELD` FOREIGN KEY (`apply_table_field`) REFERENCES `sf_dataset_fields` (`id`),
  CONSTRAINT `FK_APPLY_TABLE` FOREIGN KEY (`apply_table`) REFERENCES `sf_dataset_tables` (`id`),
  CONSTRAINT `FK_OBJECT_CONDITION` FOREIGN KEY (`object_id`) REFERENCES `sf_dataset_objects` (`id`),
  CONSTRAINT `FK_SB_OBJECT` FOREIGN KEY (`sub_object_id`) REFERENCES `sf_dataset_sub_objects` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;